### ISSUE TITLE
Failed Deployment

### ISSUE THREAD

**Issue by Jonniie** [dhruvchandak30/BookFinder#3]
Seems like your deployment has failed
![image](https://github.com/dhruvchandak30/BookFinder/assets/73708569/9639a882-b763-4552-9e28-513aafa3c855)

**Comment by dhruvchandak30** [comment]
I changed the domain to https://bookfinderlibrary.vercel.app/
Thank you, I will change it in the About Section

**Comment by Jonniie** [comment]
Alright
